### ISSUE TITLE
8.0 - crm.action - Migration error from 8.0.1.1.0

### ISSUE THREAD

**Issue by CarlesAntoli** [OCA/crm#103]
Migrating to versión 8.0.1.2.0 from version 8.0.1.1.0 crm.action module displays the following error:

`Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/openerp/service/server.py", line 936, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 142, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/odoo-dev/odoo/openerp/modules/migration.py", line 171, in migrate_module
    migrate(self.cr, pkg.installed_version)
  File "/home/odoo/odoo-dev/extra_addons/base-crm-sale/crm_action/migrations/8.0.1.2.0/pre-migration.py", line 11, in migrate
    'ALTER TABLE "crm_action_type" RENAME "is_active" TO "active"')
  File "/home/odoo/odoo-dev/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "is_active" does not exist`

Thanks

**Comment by rafaelbn** [comment]
Hi  @CarlesAntoli , could you test this fix for you issue?

https://github.com/OCA/crm/pull/137

**Comment by rafaelbn** [comment]
I'm closing as this issue is fixed in https://github.com/OCA/crm/pull/137
