### ISSUE TITLE
[11.0][crm_claim]AttributeError: module 'odoo.addons' has no attribute 'base'

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/crm#206]
Testing the `odoo` connection behind `serveo` i got this problem:

```bash
odoo.web      | Traceback (most recent call last):
odoo.web      |   File "/usr/lib/python3/dist-packages/gevent/pywsgi.py", line 884, in handle_one_response
odoo.web      |     self.run_application()
odoo.web      |   File "/usr/lib/python3/dist-packages/gevent/pywsgi.py", line 870, in run_application
odoo.web      |     self.result = self.application(self.environ, self.start_response)
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
odoo.web      |     return application_unproxied(environ, start_response)
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
odoo.web      |     result = handler(environ, start_response)
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1297, in __call__
odoo.web      |     self.load_addons()
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1319, in load_addons
odoo.web      |     m = __import__('odoo.addons.' + module)
odoo.web      |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
odoo.web      |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
odoo.web      |   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
odoo.web      |   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
odoo.web      |   File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 82, in load_module
odoo.web      |     exec(open(modfile, 'rb').read(), new_mod.__dict__)
odoo.web      |   File "<string>", line 5, in <module>
odoo.web      |   File "/var/lib/odoo/addons/11.0/crm/crm_claim/models/__init__.py", line 5, in <module>
odoo.web      |     from . import crm_claim
odoo.web      |   File "/var/lib/odoo/addons/11.0/crm/crm_claim/models/crm_claim.py", line 11, in <module>
odoo.web      |     class CrmClaim(models.Model):
odoo.web      |   File "/var/lib/odoo/addons/11.0/crm/crm_claim/models/crm_claim.py", line 65, in CrmClaim
odoo.web      |     selection=odoo.addons.base.res.res_request.referenceable_models,
odoo.web      | AttributeError: module 'odoo.addons' has no attribute 'base'
odoo.web      | {'CONTENT_LENGTH': '119',
odoo.web      |  'CONTENT_TYPE': 'application/json',
odoo.web      |  'GATEWAY_INTERFACE': 'CGI/1.1',
odoo.web      |  'HTTP_ACCEPT': 'application/json, text/javascript, */*; q=0.01',
odoo.web      |  'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
odoo.web      |  'HTTP_ACCEPT_LANGUAGE': 'es-ES,es;q=0.9',
odoo.web      |  'HTTP_CONNECTION': 'close',
odoo.web      |  'HTTP_COOKIE': 'frontend_lang=es_CO; '
odoo.web      |                 'csrftoken=FOVTYyj5elZpC0pphC9WlhWgEZ334uvirAwiEBDKTJo7n77gJhUj7DyP6kMVb1YK; '
odoo.web      |                 'sessionid=vxkrwceaixim12zwi0a5fedgx40wkioc; djdt=hide; '
odoo.web      |                 'session_id=bca828cab233dbe1c7e2204e6b9104d5a25674cc',
odoo.web      |  'HTTP_HOST': 'localhost',
odoo.web      |  'HTTP_ORIGIN': 'http://localhost',
odoo.web      |  'HTTP_REFERER': 'http://localhost/web?debug',
odoo.web      |  'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
odoo.web      |                     '(KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36',
odoo.web      |  'HTTP_X_DEBUG_MODE': '',
odoo.web      |  'HTTP_X_FORWARDED_FOR': '172.18.0.1',
odoo.web      |  'HTTP_X_FORWARDED_PROTO': 'http',
odoo.web      |  'HTTP_X_REAL_IP': '172.18.0.1',
odoo.web      |  'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
odoo.web      |  'PATH_INFO': '/longpolling/poll',
odoo.web      |  'QUERY_STRING': '',
odoo.web      |  'REMOTE_ADDR': '172.18.0.5',
odoo.web      |  'REMOTE_PORT': '46338',
odoo.web      |  'REQUEST_METHOD': 'POST',
odoo.web      |  'SCRIPT_NAME': '',
odoo.web      |  'SERVER_NAME': 'd9c112b828f8',
odoo.web      |  'SERVER_PORT': '8072',
odoo.web      |  'SERVER_PROTOCOL': 'HTTP/1.0',
odoo.web      |  'SERVER_SOFTWARE': 'gevent/1.1 Python/3.5',
odoo.web      |  'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
odoo.web      |  'wsgi.input': <gevent.pywsgi.Input object at 0x7fcc5a09ef48>,
odoo.web      |  'wsgi.multiprocess': False,
odoo.web      |  'wsgi.multithread': False,
odoo.web      |  'wsgi.run_once': False,
odoo.web      |  'wsgi.url_scheme': 'http',
odoo.web      |  'wsgi.version': (1, 0)} failed with AttributeError
odoo.web      | 
```

Why?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo-community.org/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.
