### ISSUE TITLE
Migrating Letter Management to v11

### ISSUE THREAD

**Issue by berctain** [OCA/crm#219]
Hello,
any one can help me to migrating lettermgmt v10 to v11?
I downloaded the last ver and putted it to module folders and changed all openerp values to doo
and now when i try to install it i get this error that there is no res.letter model exist
any help for next step will be great
this is the track content

-----------------------------------------------------------------

error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 335, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 993, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: model not found : res.letter

Error context:
View `Outbound Letter Tree`
[view_id: 1566, xml_id: n/a, model: res.letter, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/addons/base/ir/ir_model.py", line 1482, in _update
    record = record.create(values)
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\ model not found : res.letter\n\nError context:\nView `Outbound Letter Tree`\n[view_id: 1566, xml_id: n/a, model: res.letter, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/opt/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/tools/convert.py", line 741, in parse
    self.parse(rec, mode)
  File "/opt/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/addons/base/ir/ir_model.py", line 1482, in _update
    record = record.create(values)
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/models.py", line 3381, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/fields.py", line 1071, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/opt/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/opt/odoo/models.py", line 1040, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

model not found: res.letter

Error context:
View `Outbound Letter Tree`
[view_id: 1566, xml_id: n/a, model: res.letter, parent_id: n/a]
None" while parsing /opt/odoo/addons/lettermgmt/views/res_letter_view.xml:8, near
<record model="ir.ui.view" id="res_letter_out_tree_view">
      <field name="name">Outbound Letter Tree</field>
      <field name="model">res.letter</field>
      <field name="arch" type="xml">
        <tree string="Letters">
          <field name="name"/>
          <field name="number"/>
          <field name="move"/>
          <field name="type"/>
          <field name="class"/>
          <field name="date"/>
          <field name="recipient_partner_id"/>
          <field name="state"/>
          <field name="channel_id"/>
        </tree>
      </field>
    </record>

**Comment by pedrobaeza** [comment]
Try to follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0, but this task is quite technical and if you are not able to understand thrown errors, I'm afraid you need to know more about Odoo development.
