### ISSUE TITLE
[9.0] crm_phonecall error on install 

### ISSUE THREAD

**Issue by bodi000** [OCA/crm#240]
Hello,

While trying to install **crm_phonecall**, I get this error, due to missing dependency `openupgradelib`. I dot think I should have this installed, so I file this bug.

Thank you,
B
```

Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 660, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 697, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 333, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 326, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 976, in __call__
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\http.py", line 526, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\web\controllers\main.py", line 901, in call_button
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\web\controllers\main.py", line 889, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\module\module.py", line 460, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0\server\openerp\addons\base\module\module.py", line 535, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\registry.py", line 386, in new
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\loading.py", line 378, in load_modules
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\loading.py", line 271, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 9.0\server\.\openerp\modules\loading.py", line 145, in load_module_graph
  File "D:\odoo\linked\crm_phonecall\hooks.py", line 28, in rename_xmlids_hook
ImportError: No module named openupgradelib

```

I do not have much experience with OpenUpgrade, but it seems that the migration part included in the crm_phonecall module is not following the general approach, as openupgrade.rename_xmlids is always called from inside OpenUpgrade, not from the modules proper.

any idea?

**Comment by bodi000** [comment]
I do not have much experience with OpenUpgrade, but it seems that the migration part included in the crm_phonecall module is not following the general approach, as openupgrade.rename_xmlids is always called from inside OpenUpgrade, not from the modules proper. 

any idea?

**Comment by pedrobaeza** [comment]
openupgradelib is not the same as OpenUpgrade: this is a Python library that includes common utilities for Odoo data structures handling. It's useful for OpenUpgrade, but also for migrating between minor versions or even for several processes.

You can install it with `pip install openupgradelib`. We can do 2 things for being this bullet-proof:

* Add code in migration script for detecting before calling rename_xml_ids if there's one of these XML-IDs.
* Put in external dependencies in manifest the requirement of the library.

Feel free to propose any of them.
