### ISSUE TITLE
Lead Line Product V12

### ISSUE THREAD

**Issue by usmanfarzandali** [OCA/crm#299]
Odoo Server Error
Traceback (most recent call last):
  File "/odoo12c/odoo12c-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo12c/odoo12c-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo12c/odoo12c-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo12c/odoo12c-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo12c/odoo12c-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo12c/odoo12c-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo12c/odoo12c-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo12c/odoo12c-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo12c/odoo12c-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo12c/odoo12c-server/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo12c/odoo12c-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo12c/odoo12c-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo12c/odoo12c-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo12c/odoo12c-server/odoo/models.py", line 2774, in read
    self._read_from_database(stored, inherited)
  File "/odoo12c/odoo12c-server/odoo/models.py", line 2927, in _read_from_database
    values = [convert(value, target, validate=False) for value in values]
  File "/odoo12c/odoo12c-server/odoo/models.py", line 2927, in <listcomp>
    values = [convert(value, target, validate=False) for value in values]
  File "/odoo12c/odoo12c-server/odoo/fields.py", line 1736, in convert_to_cache
    raise TypeError("%s (field %s) must be string or datetime, not date." % (value, self))
TypeError: 2019-09-20 (field crm.product.report.date_deadline) must be string or datetime, not date.

**Comment by bodedra** [comment]
@usmanfarzandali which module and are you able to reproduce it on runbot?

**Comment by usmanfarzandali** [comment]
where i face this isssue is ... 
when i open CRM -----------> Reporting --------------> Pipeline by product 
report open -------------> then i go to Tree View/View List and open any form as oper open form i face this issue ....
===================================================
raise TypeError("%s (field %s) must be string or datetime, not date." % (value, self))
TypeError: 2019-09-20 (field crm.product.report.date_deadline) must be string or datetime, not date.
==================================================

so what i do is ... 

date_deadline = fields.Datetime('Deadline Date', readonly=True)
to 
date_deadline = fields.Date('Deadline Date', readonly=True)


why i change 
bcz 
date_deadline field come from crm.lead model in crm.lead its Date filed not Datetime field...
so i change this code as per above mention. after that report run smoothly .....

if i my action is correct i want to contribute this small effort ?
